{% set version = "0.0-3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-assertive.datetimes
  version: {{ version|replace("-", "_") }}

source:
  fn: assertive.datetimes_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/assertive.datetimes_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/assertive.datetimes/assertive.datetimes_{{ version }}.tar.gz
  sha256: 014e2162f5a8d95138ed8330f7477e71c908a29341697c09a1b7198b7e012d94

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-assertive.base >=0.0_2
    - r-assertive.types
  run:
    - r-base
    - r-assertive.base >=0.0_2
    - r-assertive.types

test:
  commands:
    - $R -e "library('assertive.datetimes')"           # [not win]
    - "\"%R%\" -e \"library('assertive.datetimes')\""  # [win]

about:
  home: https://bitbucket.org/richierocks/assertive.datetimes
  license: GPL (>= 3)
  summary: A set of predicates and assertions for checking the properties of dates and times.  This is mainly for use by other package developers who want to include run-time testing features in their own packages.  End-users will usually want to use assertive directly.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
