appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: Sbhm4uM+EhquaWMC0sR6uO53nmIuGymyDwlJwYvf1RQ822n0xHkHOY7r+frXCiOtytkaSgFqwWQPvfmI3CYm1wAxqFP+wRdNnnl8dj65PaU7hT6uU+uGOKDJ2Zxm4obeIk/vl2Hl+mTaQVPrCIAtxPSKMO0GQzq9Oq2PE/QQUSPP4ozBdrZcEGofqhdIJEDIAtE5wcwZe2nFAcLtvPq5kiunS6XXM1Tl5lmpmhVY3DSbpJh5LCY+J8nQXZMIVBdlcUT9UjXaElWGF8O2yH9iImFG1STPcU6wppoR7Dtrvr4XIWLnRtKDY2ylqyZTYR9Mt2sIUeM2PMVbdbfpuZEVEPp82Vb8jGdOtd1T2nO3IkILgYHnrn3PLBYv5Tti57NJBGBi2xwImOaz28HeBYrClj+elUC14aN1SwYz8gwRDYPx6qlkeyNXD9h/j5hXjIODVd+A0QiQ8NJHjrXCj1STY2k+kq9t6TgycArdYtk0hE5MNigbVCh1WgmxTqfxC6gLnj4/HNdEBwzZZTX10El7JJLGUw3N2WnALq1OtlzplxvxJ1qozhfSuXJgC5q2fpZWqOVHf2O4xOvYE2awyxI4RBZlLVxy5faKRNEYCAGxA3c2THnkCzEhIAWxS3cfJs96OqIZcYdvOWwtdq14gEewL6+EBe+DnEgJTfw4OFUQyJE=
conda_forge_output_validation: true
